title = "Mackrics"
base_url = "https://dev.mackrics.com"
compile_sass = false
build_search_index = false
generate_feed = true
feed_filename = "index.xml"

[markdown]
highlight_code = true
highlight_theme = "nord"

[extra]
author = "Mackrics"
