title = "Mackrics"
base_url = "https://dev.mackrics.com"
compile_sass = false
build_search_index = false
generate_feed = true
feed_filename = "index.xml"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "nord"

[extra]
author = "Mackrics"
