---
title: "How have the sanctions against Russia and their counter sanctions affected the Russian trade?"
date: "2020"
date-format: "YYYY"
---
[Link to thesis](https://gupea.ub.gu.se/bitstream/handle/2077/65246/gupea_2077_65246_1.pdf;jsessionid=979110E2FF0AB8E078100887BB0A4C34?sequence=1)

Economic sanctions are prevalent in the modern world as an alternative to war,
instead aiming to maim economic growth and power by hindering trade. In recent
times, sanctions have been imposed against many countries, Russia being one of
them. Often seen as a response to questionable political and economic acts. The
western countries and the UN being the main actors behind recent sanctions have
faced relatively small negative effects of their imposed sanctions. The
receiving countries however, often faced large consequences. With this thesis
we aim to explain how Russia was affected and possibly still is affected by the
sanctions imposed by the EU, the US, and their own counter sanctions. Searching
for patterns to see if trade was diverted and if the sanctions have had lasting
effects in a longer term. To research the question, we use descriptive
statistics and regression analysis to explain and predict the effects over
time. Our conclusions are that sanctions had a great immediate impact on trade.
In the first year a decrease of up to 31.75% in bilateral trade between Russia
and the EU and US was observed. As time passed, all parties significantly
diverted their trade to a degree. The initial trade diversion of Russia being
42.48% in the first year
