---
title: "My personal knowledge management system"
draft: true
date: 2024-01-19
date-format: iso
---

Personal knowledge management, PKM, is the methodology of organizing your
knowledge. I highly recommend reading Tiagos Fortes 
[Building a second brain](https://libro.fm/audiobooks/9781800812482-building-a-second-brain)[^1] 
for an introduction to personal knowledge management.

## Core ideas

Throughout the years I have tried various note taking styles, task management, and software
to manage my knowledge. I do not rigorously follow any methodology, but
I have gotten a lot of inspiration from the `zettelkasten method, building a second brain,
getting things done, and Cal Newport`. Based on these methods, I have some principles
I base my knowledge management on:


1. Write atomic notes
: Each note should contain a single idea, be well-written, and linkable.
Instead of repeating the same text across notes, you make a link to the
original note and instead spend time on making them high quality. Do not fear
factoring out ideas from the notes if you find that your note suddenly contain
multiple ideas.

2. Keep a working memory
: Make temporary notes whenever you think of an idea, or task, which you will
process later. This avoids watering down your system with low quality content.
You can also use these fleeting as a [rubber duck](https://en.wikipedia.org/wiki/Rubber_duck_debugging),
enabling you to keep more things in mind than you can store in short-term memory, 
see [WorkingMemory.txt](https://calnewport.com/deep-habits-workingmemory-txt-the-most-important-productivity-tool-youve-never-heard-of/).
Make sure that you regularly revies these notes, make them atomic if they are useful or remove them if no longer needed.

3. Make it easy to take and retrieve notes
: This makes it easier to save ideas and make the most of your work. I suggest
making sure you can access the system both on mobile and on a computer. Ideally,
you should be able to access it offline as well.

## Inputs

- RSS feeds
- Newsletters
- link aggregators
- Books
- Mastodon
- Random links and posts
- Commuter ideas

## Processing

- Omnivore
- `working-memory.txt`
- Miniflux

## Production

- Reading it in neovim
- sharing notes

## Consumption

- Searchable
- Application of knowledge


## Putting it all together

Input -> Processing -> Production -> Consumption

## The flow



```{mermaid}
%%| fig-align: center

%%{init: {'theme': 'base', 'themeVariables': { 'fontSize': '30px'}}}%%
%%{init: {"flowchart": {"htmlLabels": false}} }%%

flowchart TD
subgraph Input
    style Input margin-top: 10
    A(Articles)
    B(Books)
    P(Podcasts)
    R(RSS feeds)
    AB(Audiobooks)
    C(Commuting thoughts)
    S(Mastodon link)
  end
  subgraph Process
    direction LR
    %%{init:{'theme':'forest'}}%%
    A  --> O(Omnivore)
    B  --> L(Libera)
    R  --> M(Miniflux)
    M  --> O
    S  --> O
    P  --> E(Escapepod)
    AB --> V(Voice)
    O --> N((Neovim working memory))
    C --> N
    L --> N
    E --> N
    V --> N
  end
  subgraph Production["`**Production**`"]
    N --> NA(Next action)
    N --> SM(Someday maybe)
    N --> PRO(Project note)
    N --> ZK(Zettelkasten)
  end
  classDef Process fill:#fab387,stroke:#333, color: red
  class Process Process;
  classDef Production fill:#a6e3a1,stroke:#333
  class Production Production;
  classDef Input fill:#f38ba8,stroke:#333
  class Input Input;

```


[^1]: Here is an referal link to
    [libro.fm](https://libro.fm/referral?rf_code=lfm549445), it is a pretty
    cool audiobook site which let you download the audiobooks and support local
    bookstores.
