---
title: Introducing grid themes in `{ricethemes}`
date: 2023-10-18
date-format: iso
---

If you have not already checked out [`{ricethemes}`](https://github.com/mackrics/ricethemes),
check out my [blog post introducing it](./ricethemes-intro.qmd).

Usually when making plots, I am not interested in the precise values on either
the x or y axis. Therefore, I do not usually use grid lines since they are not
neseccary to spot general trends and plots usually look better without them. However,
on some occasions I want to know the value of a specific observation and therefore
need grid lines.

I have now added a theme (with four flavors) in `{ricethemes}` with grid lines.
I tried making the themes relatively minimal by not adding any axis lines and
having a single color for both the minor and major grid lines. I decided on
grid lines for both the x and y axis to make this theme a bit more practical
and universal.

The grid lines are in a slightly brighter (darker for the latte flavor) color
so that the main background could remain the same. The purpose of this is to
make the grid lines visible, yet unintrusive. 

If you have already installed `{ricethemes}`, update it with the following
command to get the latest themes, which you can also use to install it if you
have not already:

```r
pak::pkg_install("mackrics/ricethemes")
```

Enjoy!


```{r}
#| panel: tabset
#| output: asis
#| fig-align: center
#| out-width: "100%"
library(ricethemes)
library(ggplot2)
library(tibble)


plotlist2 <-
  tibble(ctp_mocha, ctp_macchiato, ctp_frappe, ctp_latte) |>
  lapply(\(ctp_theme)
    ggplot(cars) +
    aes(speed, dist) +
    geom_point(color = {{ ctp_theme }}[["yellow"]]) +
    geom_smooth(
      method = "lm",
      se = FALSE,
      formula = "y ~ x",
      color = {{ ctp_theme }}[["peach"]]
    ) +
    theme_ctp_grid({{ ctp_theme }}) +
    labs(x = "Speed", y = "Distance")
  )

for (i in seq(1, length(plotlist2))) {
  cat("\n\n#", names(plotlist2)[[ i ]], "\n")
  print(plotlist2[[ i ]])
}
```
