---
title: My favorite open source tools
date: 9999-12-31
date-format: iso
---

## R
[R](https://www.r-project.org/) is a programming language for statistical computing.
I use R in my daily work, personal projects, and when I studied. Beside 
hands-on experience, I enjoy learning new techniques through
[The Big Book of R](https://www.bigbookofr.com/).

Here are some stuff I have used R for:

- Conduct econometric estimations such as:
  [OLS](https://en.wikipedia.org/wiki/Ordinary_least_squares),
  [GMM](https://en.wikipedia.org/wiki/Generalized_method_of_moments), 
  [Instrument variables estimations](https://en.wikipedia.org/wiki/Instrumental_variables_estimation),
  and [Merger simulations](https://en.wikipedia.org/wiki/Merger_simulation).
- Manage complex data structures by working with nested data.
- Clean data.
- Create interactive command line interface applications to speed up manual
  tasks and learn new concepts.
- Working with various application programming interface to automate workflows.


## Git
[Git](https://git-scm.com) is a version control system which I have used for
professional, academic, and personal projects. Git enables granular control
of the history of code documents and is also a nice platform for sharing code
and collaborating. A very nice resource for learning about Git is the [Pro
Git](https://git-scm.com/book/en/v2).

## Quarto
[Quarto](https://quarto.org/) is a scientific typesetting system which enables
literate programming. It is a very efficient way to generate reports,
presentations, books, and websites, since code and text can be combined into a
single document. By combining code and text into a single document, the document
also become more reproducible.

## Shell
I prefer to manage most things via the command line. I use GNU/Linux on my
personal machines and have used a wide variety of shells such as bash, fish,
and mksh on them. I have also some experience using PowerShell on Windows
machines. I use shell to manage files, script smaller repetitive tasks, and
for smaller data exploration tasks.
