name: build site

on:
  push:
    branches:
      - litedown
  pull_request:
    branches:
      - litedown

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout litedown branch
      uses: actions/checkout@v4
      with:
        ref: litedown
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
    - name: install sysreqss
      run:
        sudo apt-get update;
        sudo apt-get install -y fontconfig libfreetype6 libcairo2-dev libpng-dev libcurl4-openssl-dev openssl make pandoc libv8-dev libxml2
    - name: Install pak, deps, render site.
      run: |
        sudo Rscript -e 'install.packages("pak", repos = sprintf("https://r-lib.github.io/p/pak/stable/%s/%s/%s", .Platform$pkgType, R.Version()$os, R.Version()$arch));
        Sys.setenv(PKG_SYSREQS = FALSE);
        pak::lockfile_install();
        litedown::fuse_site()'
    - name: Setup dir
      run: |
        mkdir site
        mkdir site/blog
        rm *.Rmd
        mv *.html site
        rm blog/*.Rmd -fr
        sudo mv blog/* site/blog
        mv *.txt site
    - name:  Setup ssh
      run: | 
          mkdir -p ~/.ssh
          echo $PRIVATE_SSH_KEY > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 $SSH_HOST >> ~/.ssh/known_hosts
          sudo apt-get install sshpass
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/is_rsa
      env: 
        build: 
          ${{ secrets.PRIVATE_SSH_KEY }}
          ${{ secrets.SSH_HOST }}
    - name: Sync
      run: rsync -avx --delete site/ $SSH_USERERNAME@$SSH_HOST:$SSH_PATH
      env: 
        build: 
            ${{ secrets.SSH_USERNAME }}
            ${{ secrets.SSH_HOST }}
            ${{ secrets.SSH_PATH }}
