name: Build Site

on:
  push:
    branches:
      - litedown  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          R-version: '4.4.1'
          
      - name: Set site library path
        run: |
          lib <- Sys.getenv("R_LIBS_SITE")
          if (lib == "") {
            lib <- file.path(Sys.getenv("HOME"), "R", "site-library")  # Use a writable path
            dir.create(lib, recursive = TRUE, showWarnings = FALSE)  # Create the directory if it doesn't exist
            cat(sprintf("R_LIBS_SITE=%s\n", lib), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
            cat(sprintf("R_LIB_FOR_PAK=%s\n", lib), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
            message("Setting R_LIBS_SITE to ", lib)
          } else {
            message("R_LIBS_SITE is already set to ", lib)
            cat(sprintf("R_LIB_FOR_PAK=%s\n", strsplit(lib, .Platform$path.sep)[[1]][[1]]), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
          }
          if (nchar(Sys.getenv("R_LIBS_USER")) == 0) {
            message("R_LIBS_USER GH env var is unset, setting now: ", Sys.getenv("R_LIBS_USER"))
            cat(sprintf("R_LIBS_USER=%s\n", Sys.getenv("R_LIBS_USER")), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
          } else {
            message("R_LIBS_USER GH env var is already set: ", Sys.getenv("R_LIBS_USER"))
          }'

      - name: Install pak
        run: |
          echo "::group::Install pak"
          R -q -e 'dir.create(Sys.getenv("R_LIB_FOR_PAK"), recursive = TRUE, showWarnings = FALSE)'
          R -q -e 'install.packages("pak", lib = Sys.getenv("R_LIB_FOR_PAK"), repos = "https://r-lib.github.io/p/pak/latest")'
          echo "::endgroup::"

      - name: Install dependencies
        run: |
          Rscript -e 'message("::group::Install/update packages")'
          Rscript -e 'Sys.setenv("PKGCACHE_HTTP_VERSION" = "2")'
          Rscript -e 'library(pak, lib.loc = Sys.getenv("R_LIB_FOR_PAK"))'
          Rscript -e 'pak::lockfile_install()'
          Rscript -e 'message("::endgroup::")'

      - name: Render Markdown and Generate RSS Feed
        run: |
          Rscript -e 'litedown::fuse_site()'
          Rscript -e '
          source("R/gen_rss_feed.R")
          get_rss_items("https://dev.mackrics.com/blog") |> 
            gen_feed("Mackrics", "https://dev.mackrics.com/blog") |>
            write("index.xml")
          '

      - name: Commit and push changes to deploy branch
        run: |
          git config --local user.email "hello@mackrics.com"
          git config --local user.name "mackrics"
          git add .
          git commit -m "Update site"
          git push origin HEAD:deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
