name: build dev site

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout dev branch
      uses: actions/checkout@v4
      with:
        ref: dev
    - name: 'build'
      uses: shalzz/zola-deploy-action@master
      env:
        BUILD_DIR: .
        TOKEN: ${{ secrets.TOKEN }}
        BUILD_ONLY: true
    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-avx --delete"
        SOURCE: "public/"
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_USER: ${{ secrets.SSH_USERNAME }}
        TARGET: ./dev/
        EXCLUDE: ".ssh"
        SCRIPT_BEFORE: |
          whoami
          ls -al
        SCRIPT_AFTER: |
          whoami
          ls -al
          echo $RSYNC_STDOUT
